{
 "title": "MongoDB Second Level Monitoring",
 "tags": [ "MongoDB" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "mongodb_sharding",
    "label": "mongodb_sharding",
    "query": "label_values(mongodb_sharding{all{hid=0, pid=0}},mongodb_sharding)"
   },
   {
    "name": "mongodb_cluster",
    "label": "mongodb_cluster",
    "query": "label_values(mongodb_cluster{$mongodb_sharding},mongodb_cluster)"
   },
   {
    "name": "mongodb_instance",
    "label": "mongodb_instance",
    "query": "label_values(mongodb_instance{$mongodb_cluster},mongodb_instance)"
   },
   { "name": "filter", "label": "filter", "query": "fix, peak" }
  ]
 },
 "panels": [
  { "title": "Recent Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "current connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|connections|current{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "available connection",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|connections|available{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|uptime{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "slave delay",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|members|PRIMARY+|optime|ts;\nmongodb|members|SECONDARY+true|optime|ts;\n[arraySub($2, $1)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "WiredTiger Max Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|maximum bytes configured{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "WiredTiger Current Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|bytes currently in the cache{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "WiredTiger Dirty Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|tracked dirty bytes in the cache{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|bytes currently in the cache;\nmongodb|wiredTiger|cache|maximum bytes configured;\n[arrayDiv(arrayDigitMul($1, 100),$2)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb|mem|virtual;\nmongodb|mem|resident;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "connections usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|connections|current;\nmongodb|connections|available;\nmongodb|connections|internal_current;\nmongodb|connections|internal_available;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb|network|bytesIn;\nmongodb|network|bytesOut;\nmongodb|network|physicalBytesIn;\nmongodb|network|physicalBytesOut;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "slave delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb|members|PRIMARY+|optime|ts;\nmongodb|members|SECONDARY+true|optime|ts;\n[arraySub($2, $1)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "delay"
    }
   ]
  },
  {
   "title": "cache usage percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|bytes currently in the cache;\nmongodb|wiredTiger|cache|maximum bytes configured\n[arrayDiv(arrayDigitMul($1, 100), $2)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "cache usage percent"
    },
    {
     "expr": "mongodb|wiredTiger|cache|tracked dirty bytes in the cache;\nmongodb|wiredTiger|cache|maximum bytes configured\n[arrayDiv(arrayDigitMul($1, 100), $2)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "dirty cache usage percent"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|extra_info|page_faults;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Opcounters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Opcounters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|opcounters|query;\nmongodb|opcounters|insert;\nmongodb|opcounters|update;\nmongodb|opcounters|delete;\nmongodb|opcounters|getmore;\nmongodb|opcounters|command;\nmongodb|metrics|repl|apply|ops;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Document", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Mongod - Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|metrics|document|inserted;\nmongodb|metrics|document|updated;\nmongodb|metrics|document|deleted;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "commands",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reg(mongodb\\|metrics\\|commands\\|.*\\|total$)\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field3}}"
    }
   ]
  },
  { "title": "Curosr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "WiredTiger cursor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reg(mongodb\\|wiredTiger\\|cursor\\|.*)\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Scanned & Moved", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Mongod - Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|metrics|queryExecutor|scanned;\nmongodb|metrics|queryExecutor|scannedObjects;\nmongodb|metrics|record|moves;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Lock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Locks acquire count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|locks|Database|acquireCount|W;\nmongodb|locks|Collection|acquireCount|W;\nmongodb|locks|Global|acquireCount|W;\nmongodb|locks|Global|acquireCount|w;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field2}} {{field4}}"
    }
   ]
  },
  {
   "title": "Locks acquireWaitcount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|locks|Database|acquireWaitCount|W;\nmongodb|locks|Collection|acquireWaitCount|W;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field2}}|{{field4}}"
    }
   ]
  },
  { "title": "GlobalLock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "GlobalLock currentQueue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|globalLock|currentQueue|total;\nmongodb|globalLock|currentQueue|writers;\nmongodb|globalLock|currentQueue|readers;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mongod - Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|globalLock|currentQueue|total;\nmongodb|globalLock|currentQueue|readers;\nmongodb|globalLock|currentQueue|writers;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field3}}"
    }
   ]
  },
  {
   "title": "GlobalLock activeClients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|globalLock|activeClients|total;\nmongodb|globalLock|activeClients|writers;\nmongodb|globalLock|activeClients|readers;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Transanctions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "WiredTiger Concurrent Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|concurrentTransactions|write|available;\nmongodb|wiredTiger|concurrentTransactions|write|out;\nmongodb|wiredTiger|concurrentTransactions|read|available;\nmongodb|wiredTiger|concurrentTransactions|read|out;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field3}}|{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|transaction|transactions committed;\nmongodb|wiredTiger|transaction|transactions rolled back;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|transaction|transaction checkpoint scrub time (msecs);\nmongodb|wiredTiger|transaction|transaction checkpoint max time (msecs);\nmongodb|wiredTiger|transaction|transaction checkpoint total time (msecs);\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shard Split Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Split Metrics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|metrics|commands|splitVector|total;\nmongodb|metrics|commands|splitVector|failed;\nmongodb|metrics|commands|splitChunk|total;\nmongodb|metrics|commands|splitChunk|failed;\nmongodb|metrics|commands|moveChunk|total;\nmongodb|metrics|commands|moveChunk|failed;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{field3}}|{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "WiredTiger Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|bytes read into cache;\nmongodb|wiredTiger|cache|bytes written from cache;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|eviction server evicting pages;\nmongodb|wiredTiger|cache|eviction worker thread evicting pages;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|cache|pages read into cache;\nmongodb|wiredTiger|cache|pages written from cache;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "WiredTIger Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "WiredTiger Log Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|log|log bytes written\n[arrayDiff($1)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|log|log records compressed;\nmongodb|wiredTiger|log|log records not compressed;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Log Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|log|log write operations;\nmongodb|wiredTiger|log|log flush operations;\nmongodb|wiredTiger|log|log sync operations;\nmongodb|wiredTiger|log|log scan operations;\nmongodb|wiredTiger|log|log force write operations;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Thread Yield", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Thread Yield Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|thread-yield|application thread time evicting (usecs);\nmongodb|wiredTiger|thread-yield|application thread time waiting for cache (usecs);\nmongodb|wiredTiger|thread-yield|page acquire time sleeping (usecs);\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread Yield Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|thread-yield|page acquire busy blocked;\nmongodb|wiredTiger|thread-yield|page acquire eviction blocked;\nmongodb|wiredTiger|thread-yield|page acquire locked blocked;\nmongodb|wiredTiger|thread-yield|page acquire read blocked;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "WiredTiger Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "WiredTiger Block Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|block-manager|bytes read;\nmongodb|wiredTiger|block-manager|bytes written;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WiredTiger Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|session|open cursor count;\nmongodb|wiredTiger|session|open session count;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Document", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Connection I/Os",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|connection|total read I/Os;\nmongodb|wiredTiger|connection|total write I/Os;\nmongodb|wiredTiger|connection|total fsync I/Os;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "connection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|connection|auto adjusting condition resets;\nmongodb|wiredTiger|connection|auto adjusting condition wait calls;\nmongodb|wiredTiger|connection|pthread mutex condition wait calls;\nmongodb|wiredTiger|connection|pthread mutex shared lock read-lock calls;\nmongodb|wiredTiger|connection|pthread mutex shared lock write-lock calls;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "cache and conn history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "connection files open",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|connection|files currently open\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "connection memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|connection|memory allocations;\nmongodb|wiredTiger|connection|memory frees;\nmongodb|wiredTiger|connection|memory re-allocations;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "mongod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "block-manager blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|block-manager|blocks pre-loaded;\nmongodb|wiredTiger|block-manager|blocks read;\nmongodb|wiredTiger|block-manager|blocks written;\nmongodb|wiredTiger|block-manager|mapped blocks read;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "block-manager bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|block-manager|bytes written for checkpoint;\nmongodb|wiredTiger|block-manager|bytes read;\nmongodb|wiredTiger|block-manager|bytes written;\nmongodb|wiredTiger|block-manager|mapped bytes read;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Global Lock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "concurrentTransactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|concurrentTransactions|write|available;\nmongodb|wiredTiger|concurrentTransactions|read|available;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{field3}}|{{name}}"
    }
   ]
  },
  {
   "title": "thread-state active filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb|wiredTiger|thread-state|active filesystem fsync calls;\nmongodb|wiredTiger|thread-state|active filesystem read calls;\nmongodb|wiredTiger|thread-state|active filesystem write calls;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "reconciliation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 188 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|reconciliation|fast-path pages deleted;\nmongodb|wiredTiger|reconciliation|pages deleted;\nmongodb|wiredTiger|reconciliation|page reconciliation calls;\nmongodb|wiredTiger|reconciliation|page reconciliation calls for eviction;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "mongodb|wiredTiger|reconciliation|split objects currently awaiting free;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "transanctions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "collapsed": true,
   "panels": [
    {
     "title": "transaction checkpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 189 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|transaction|transaction checkpoint most recent time (msecs);\nmongodb|wiredTiger|transaction|transaction checkpoint scrub time (msecs);\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "mongodb|wiredTiger|transaction|transaction checkpoint total time (msecs);\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 },
   "collapsed": true,
   "panels": [
    {
     "title": "transaction calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 190 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|transaction|transactions committed;\nmongodb|wiredTiger|transaction|transactions rolled back;\nmongodb|wiredTiger|transaction|transaction sync calls;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "transaction snapshot",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 190 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|transaction|number of named snapshots created;\nmongodb|wiredTiger|transaction|number of named snapshots dropped;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "collapsed": true,
   "panels": [
    {
     "title": "transaction checkpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 191 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|transaction|transaction begins;\nmongodb|wiredTiger|transaction|transaction checkpoint currently running;\nmongodb|wiredTiger|transaction|transaction checkpoints;\nmongodb|wiredTiger|transaction|transaction checkpoint generation;\nmongodb|wiredTiger|transaction|transaction checkpoint scrub dirty target;\nmongodb|wiredTiger|transaction|transaction checkpoints skipped because database was clean;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "transaction ranges of IDs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 191 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|transaction|transaction range of IDs currently pinned;\nmongodb|wiredTiger|transaction|transaction range of IDs currently pinned by a checkpoint;\nmongodb|wiredTiger|transaction|transaction range of IDs currently pinned by named snapshots;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "collapsed": true,
   "panels": [
    {
     "title": "log slots",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|busy returns attempting to switch slots;\nmongodb|wiredTiger|log|consolidated slot closures;\nmongodb|wiredTiger|log|consolidated slot join active slot closed;\nmongodb|wiredTiger|log|consolidated slot join races;\nmongodb|wiredTiger|log|consolidated slot join transitions;\nmongodb|wiredTiger|log|consolidated slot joins;\nmongodb|wiredTiger|log|consolidated slot transitions unable to find free slot;\nmongodb|wiredTiger|log|consolidated slot unbuffered writes;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "data-handle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 192 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|data-handle|connection sweep candidate became referenced;\nmongodb|wiredTiger|data-handle|connection sweep dhandles closed;\nmongodb|wiredTiger|data-handle|connection sweep dhandles removed from hash list;\nmongodb|wiredTiger|data-handle|connection sweep time-of-death sets;\nmongodb|wiredTiger|data-handle|connection sweeps;\nmongodb|wiredTiger|data-handle|session dhandles swept;\nmongodb|wiredTiger|data-handle|session sweep attempts;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "mongodb|wiredTiger|data-handle|connection data handles currently active;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 },
   "collapsed": true,
   "panels": [
    {
     "title": "log operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log scan records requiring two reads;\nmongodb|wiredTiger|log|log server thread advances write LSN;\nmongodb|wiredTiger|log|log server thread write LSN walk skipped;\nmongodb|wiredTiger|log|log force write operations skipped;\nmongodb|wiredTiger|log|log force write operations;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "log operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log force write operations;\nmongodb|wiredTiger|log|log flush operations;\nmongodb|wiredTiger|log|log scan operations;\nmongodb|wiredTiger|log|log flush operations;\nmongodb|wiredTiger|log|log sync operations;\nmongodb|wiredTiger|log|log write operations;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "collapsed": true,
   "panels": [
    {
     "title": "log records",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 194 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log records compressed;\nmongodb|wiredTiger|log|log records not compressed;\nmongodb|wiredTiger|log|log records too small to compress;\nmongodb|wiredTiger|log|records processed by log scan;\nmongodb|wiredTiger|log|written slots coalesced;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "log sync time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 194 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log sync time duration (usecs);\nmongodb|wiredTiger|log|log sync_dir time duration (usecs);\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "collapsed": true,
   "panels": [
    {
     "title": "log write",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 195 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log bytes written;\nmongodb|wiredTiger|log|log bytes of payload data;\nmongodb|wiredTiger|log|logging bytes consolidated;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "log files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 195 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|log files manually zero-filled;\nmongodb|wiredTiger|log|number of pre-allocated log files to create;\nmongodb|wiredTiger|log|pre-allocated log files not ready and missed;\nmongodb|wiredTiger|log|pre-allocated log files prepared;\nmongodb|wiredTiger|log|pre-allocated log files used;\nmongodb|wiredTiger|log|yields waiting for previous log file close;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 },
   "collapsed": true,
   "panels": [
    {
     "title": "log sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 196 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|total in-memory size of compressed records;\nmongodb|wiredTiger|log|total log buffer size;\nmongodb|wiredTiger|log|total size of compressed records;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "log yields wait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 196 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|log|yields waiting for previous log file close\n[arrayDiff($1)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "collapsed": true,
   "panels": [
    {
     "title": "lock acquisitions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 197 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|lock|checkpoint lock acquisitions;\nmongodb|wiredTiger|lock|metadata lock acquisitions;\nmongodb|wiredTiger|lock|schema lock acquisitions;\nmongodb|wiredTiger|lock|table lock acquisitions;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "lock acquisitions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 197 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|lock|checkpoint lock application thread wait time (usecs);\nmongodb|wiredTiger|lock|checkpoint lock internal thread wait time (usecs);\nmongodb|wiredTiger|lock|handle-list lock eviction thread wait time (usecs);\nmongodb|wiredTiger|lock|metadata lock application thread wait time (usecs);\nmongodb|wiredTiger|lock|metadata lock internal thread wait time (usecs);\nmongodb|wiredTiger|lock|schema lock application thread wait time (usecs);\nmongodb|wiredTiger|lock|schema lock internal thread wait time (usecs);\nmongodb|wiredTiger|lock|table lock application thread time waiting for the table lock (usecs);\nmongodb|wiredTiger|lock|table lock internal thread time waiting for the table lock (usecs)\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "collapsed": true,
   "panels": [
    {
     "title": "session",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 198 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|session|table alter successful calls;\nmongodb|wiredTiger|session|table compact successful calls;\nmongodb|wiredTiger|session|table create successful calls;\nmongodb|wiredTiger|session|table drop successful calls;\nmongodb|wiredTiger|session|table rebalance successful calls;\nmongodb|wiredTiger|session|table rename successful calls;\nmongodb|wiredTiger|session|table salvage successful calls;\nmongodb|wiredTiger|session|table truncate successful calls;\nmongodb|wiredTiger|session|table verify successful calls;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "mongodb|wiredTiger|session|open cursor count;\nmongodb|wiredTiger|session|open session count;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "session failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 198 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|session|table alter unchanged and skipped;\nmongodb|wiredTiger|session|table compact failed calls;\nmongodb|wiredTiger|session|table create failed calls;\nmongodb|wiredTiger|session|table drop failed calls;\nmongodb|wiredTiger|session|table rebalance failed calls;\nmongodb|wiredTiger|session|table rename failed calls;\nmongodb|wiredTiger|session|table salvage failed calls;\nmongodb|wiredTiger|session|table truncate failed calls;\nmongodb|wiredTiger|session|table verify failed calls;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache read write count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 199 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|application threads page read from disk to cache count;\nmongodb|wiredTiger|cache|application threads page write from cache to disk count;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "cache read write time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 199 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|application threads page read from disk to cache time (usecs);\nmongodb|wiredTiger|cache|application threads page write from cache to disk time (usecs);\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache page",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|pages queued for eviction;\nmongodb|wiredTiger|cache|pages read into cache;\nmongodb|wiredTiger|cache|pages requested from the cache;\nmongodb|wiredTiger|cache|pages written from cache;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache pages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|bytes read into cache;\nmongodb|wiredTiger|block-manager|bytes read;\nmongbdo|wiredTiger|cache|bytes written from cache;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "collapsed": true,
   "panels": [
    {
     "title": "WiredTiger Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 202 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|checkpoint blocked page eviction;\nmongodb|wiredTiger|cache|eviction server evicting pages;\nmongodb|wiredTiger|cache|eviction worker thread evicting pages;\nmongodb|wiredTiger|cache|modified pages evicted by application threads;\nmongodb|wiredTiger|cache|unmodified pages evicted;\nmongodb|wiredTiger|cache|modified pages evicted;\nmongodb|wiredTiger|cache|internal pages evicted;\nmongodb|wiredTiger|cache|pages evicted because they had chains of deleted items;\nmongodb|wiredTiger|cache|pages evicted because they exceeded the in-memory maximum;\n[arrayDiff($0)]\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "collapsed": true,
   "panels": [
    {
     "title": "maximum page size at eviction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|maximum page size at eviction\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "cache page",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|pages currently held in the cache;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 204 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|bytes belonging to page images in the cache;\nmongodb|wiredTiger|cache|bytes not belonging to page images in the cache;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "eviction worker thread",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 204 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb|wiredTiger|cache|eviction worker thread active;\nmongodb|wiredTiger|cache|eviction worker thread stable number;\n{hostId=$mongodb_cluster,host=$mongodb_instance,filter=$filter}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}